# Auto-generated Android.mk for Samsung A04s vendor prebuilts
# Covers 389 removed .so and /bin/ entries from a04s-vendor.mk
# Fixes: ELF invalid alignment + 'not in allowed directory' errors
#
# Generated by Claude — do not edit manually

LOCAL_PATH := $(call my-dir)

# ==========================================================
# VENDOR SHARED LIBRARIES — 32-bit AND 64-bit (MULTILIB BOTH)
# ==========================================================

# Template macro: args = stem subdir
define define-vendor-lib-both
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := both
  LOCAL_SRC_FILES_32        := proprietary/vendor/lib/$(if $(2),$(2)/)$(1).so
  LOCAL_SRC_FILES_64        := proprietary/vendor/lib64/$(if $(2),$(2)/)$(1).so
  $(if $(2),LOCAL_MODULE_RELATIVE_PATH := $(2))
  include $$(BUILD_PREBUILT)
endef

# vendor/lib/ — 85 libs
$(eval $(call define-vendor-lib-both,libBeauty_v4.camera.samsung,))
$(eval $(call define-vendor-lib-both,libDualCamBokehCapture.camera.samsung,))
$(eval $(call define-vendor-lib-both,libExynosHWCService_samsung,))
$(eval $(call define-vendor-lib-both,libFaceService,))
$(eval $(call define-vendor-lib-both,libFace_Landmark_API.camera.samsung,))
$(eval $(call define-vendor-lib-both,libHprFace_GAE_api.camera.samsung,))
$(eval $(call define-vendor-lib-both,libHpr_RecGAE_cvFeature_v1.0.camera.samsung,))
$(eval $(call define-vendor-lib-both,libLocalTM_capture_core.camera.samsung,))
$(eval $(call define-vendor-lib-both,libLocalTM_wrapper.camera.samsung,))
$(eval $(call define-vendor-lib-both,libOpenCv.camera.samsung,))
$(eval $(call define-vendor-lib-both,libSEF.quram,))
$(eval $(call define-vendor-lib-both,lib_SoundAlive_3DPosition_ver202,))
$(eval $(call define-vendor-lib-both,lib_SoundAlive_AlbumArt_ver105,))
$(eval $(call define-vendor-lib-both,lib_SoundAlive_play_plus_ver500,))
$(eval $(call define-vendor-lib-both,lib_SoundBooster_ver1100,))
$(eval $(call define-vendor-lib-both,libbauthserver,))
$(eval $(call define-vendor-lib-both,libbauthtzcommon,))
$(eval $(call define-vendor-lib-both,libbeautyshot.arcsoft,))
$(eval $(call define-vendor-lib-both,libbt-vendor-samsung,))
$(eval $(call define-vendor-lib-both,libegis_fp_normal_sensor_test,))
$(eval $(call define-vendor-lib-both,libeis_core,))
$(eval $(call define-vendor-lib-both,libepicoperator,))
$(eval $(call define-vendor-lib-both,libexifa.camera.samsung,))
$(eval $(call define-vendor-lib-both,libexynoscamera_plugin,))
$(eval $(call define-vendor-lib-both,libexynoscamera_plugin_utils,))
$(eval $(call define-vendor-lib-both,libexynoscamera_tdnr_plugin,))
$(eval $(call define-vendor-lib-both,libface_landmark_lite.arcsoft,))
$(eval $(call define-vendor-lib-both,libfloatingfeature,))
$(eval $(call define-vendor-lib-both,libgf_in_system_lib,))
$(eval $(call define-vendor-lib-both,libgpudataproducer,))
$(eval $(call define-vendor-lib-both,libhdrwrapper,))
$(eval $(call define-vendor-lib-both,libheifcapture,))
$(eval $(call define-vendor-lib-both,libimagecodec_native.quram,))
$(eval $(call define-vendor-lib-both,liblivefocus_capture_engine,))
$(eval $(call define-vendor-lib-both,liblivefocus_preview_engine,))
$(eval $(call define-vendor-lib-both,liblivefocus_preview_interface,))
$(eval $(call define-vendor-lib-both,libmfb,))
$(eval $(call define-vendor-lib-both,libmpbase,))
$(eval $(call define-vendor-lib-both,libpadm,))
$(eval $(call define-vendor-lib-both,libphotohdr,))
$(eval $(call define-vendor-lib-both,libphotohdrcp,))
$(eval $(call define-vendor-lib-both,libprofileparamstorage,))
$(eval $(call define-vendor-lib-both,libqfp_sensortest,))
$(eval $(call define-vendor-lib-both,libremosaic_wrapper,))
$(eval $(call define-vendor-lib-both,libsavsac,))
$(eval $(call define-vendor-lib-both,libsavscmn,))
$(eval $(call define-vendor-lib-both,libsavsvc,))
$(eval $(call define-vendor-lib-both,libsecaudiocoreutils,))
$(eval $(call define-vendor-lib-both,libsecaudioinfo,))
$(eval $(call define-vendor-lib-both,libsecfr_engine,))
$(eval $(call define-vendor-lib-both,libsecfr_model,))
$(eval $(call define-vendor-lib-both,libsecnativefeature,))
$(eval $(call define-vendor-lib-both,libsecril-client,))
$(eval $(call define-vendor-lib-both,libsehbluetooth_audio_session_aidl,))
$(eval $(call define-vendor-lib-both,libsemnativecarrierfeature,))
$(eval $(call define-vendor-lib-both,libsimba.media.samsung,))
$(eval $(call define-vendor-lib-both,libsnaace,))
$(eval $(call define-vendor-lib-both,libsnamrnb,))
$(eval $(call define-vendor-lib-both,libsnamrwb,))
$(eval $(call define-vendor-lib-both,libspatializerparamstorage,))
$(eval $(call define-vendor-lib-both,libspeakercalibration,))
$(eval $(call define-vendor-lib-both,libsynaFpSensorTestNwd,))
$(eval $(call define-vendor-lib-both,libteecl,))
$(eval $(call define-vendor-lib-both,libucm_tlc_comm,))
$(eval $(call define-vendor-lib-both,libucm_tlc_direct_comm,))
$(eval $(call define-vendor-lib-both,libucm_tlc_tz_esecomm,))
$(eval $(call define-vendor-lib-both,libuniplugin,))
$(eval $(call define-vendor-lib-both,libvideobeauty.arcsoft,))
$(eval $(call define-vendor-lib-both,libvideobeauty_interface,))
$(eval $(call define-vendor-lib-both,libwrappergps,))
$(eval $(call define-vendor-lib-both,mali_symlink,))
$(eval $(call define-vendor-lib-both,sensors.grip,))
$(eval $(call define-vendor-lib-both,sensors.inputvirtual,))
$(eval $(call define-vendor-lib-both,sensors.sensorhub,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.audio@1.0,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.biometrics.face-V3-ndk,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.bluetooth.audio-V2-ndk,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.bluetooth.audio-impl,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.security.drk@2.0,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.tlc.ucm@2.0,))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.tlc.ucm@2.0-impl,))
$(eval $(call define-vendor-lib-both,vendor.samsung_slsi.hardware.epic-V1-ndk,))
$(eval $(call define-vendor-lib-both,vendor.samsung_slsi.hardware.epic@1.0,))

# vendor/lib/egl/ — 1 libs
$(eval $(call define-vendor-lib-both,libGLES_mali,egl))

# vendor/lib/hw/ — 6 libs
$(eval $(call define-vendor-lib-both,audio.sec_primary.default,hw))
$(eval $(call define-vendor-lib-both,gatekeeper.exynos850,hw))
$(eval $(call define-vendor-lib-both,hwcomposer.exynos850,hw))
$(eval $(call define-vendor-lib-both,sensors.exynos850,hw))
$(eval $(call define-vendor-lib-both,vendor.samsung.hardware.audio@1.0-impl,hw))
$(eval $(call define-vendor-lib-both,vulkan.mali,hw))

# vendor/lib/omx/ — 1 libs
$(eval $(call define-vendor-lib-both,libOMX.Exynos.HEVC.Encoder,omx))

# vendor/lib/soundfx/ — 6 libs
$(eval $(call define-vendor-lib-both,libaudioeffectoffload,soundfx))
$(eval $(call define-vendor-lib-both,libaudiosaplus_sec,soundfx))
$(eval $(call define-vendor-lib-both,libmyspace,soundfx))
$(eval $(call define-vendor-lib-both,libsamsungSoundbooster_plus,soundfx))
$(eval $(call define-vendor-lib-both,libswdap,soundfx))
$(eval $(call define-vendor-lib-both,libswspatializer,soundfx))

# ==========================================================
# VENDOR SHARED LIBRARIES — 32-bit ONLY
# ==========================================================

define define-vendor-lib32
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := 32
  LOCAL_SRC_FILES_32        := proprietary/vendor/lib/$(if $(2),$(2)/)$(1).so
  $(if $(2),LOCAL_MODULE_RELATIVE_PATH := $(2))
  include $$(BUILD_PREBUILT)
endef

# vendor/lib/ — 21 libs
$(eval $(call define-vendor-lib32,libBufferStats,))
$(eval $(call define-vendor-lib32,libFrucSSMLib,))
$(eval $(call define-vendor-lib32,libSamsungPostProcessConvertor,))
$(eval $(call define-vendor-lib32,libSecRecorder,))
$(eval $(call define-vendor-lib32,lib_SamsungRec_07010,))
$(eval $(call define-vendor-lib32,lib_SoundAlive_SRC384_ver320,))
$(eval $(call define-vendor-lib32,lib_soundaliveresampler,))
$(eval $(call define-vendor-lib32,libaboxpcmdump,))
$(eval $(call define-vendor-lib32,libalsautils_sec,))
$(eval $(call define-vendor-lib32,libaudioparamupdate,))
$(eval $(call define-vendor-lib32,libaudioproxy,))
$(eval $(call define-vendor-lib32,libcodecsolutionhelper_vendor,))
$(eval $(call define-vendor-lib32,libdatamod,))
$(eval $(call define-vendor-lib32,liblastaboxmsg,))
$(eval $(call define-vendor-lib32,liboemcrypto,))
$(eval $(call define-vendor-lib32,libpredeflicker_native,))
$(eval $(call define-vendor-lib32,librecordalive,))
$(eval $(call define-vendor-lib32,libstagefright_bufferqueue_helper_vendor,))
$(eval $(call define-vendor-lib32,libwvhidl,))
$(eval $(call define-vendor-lib32,vintf-codecsolution-V2-ndk,))

# vendor/lib/hw/ — 1 libs
$(eval $(call define-vendor-lib32,audio.primary.exynos850,hw))

# ==========================================================
# VENDOR SHARED LIBRARIES — 64-bit ONLY
# ==========================================================

define define-vendor-lib64
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := 64
  LOCAL_SRC_FILES_64        := proprietary/vendor/lib64/$(if $(2),$(2)/)$(1).so
  $(if $(2),LOCAL_MODULE_RELATIVE_PATH := $(2))
  include $$(BUILD_PREBUILT)
endef

# vendor/lib64/ — 91 libs
$(eval $(call define-vendor-lib64,libSecC2ComponentStore,))
$(eval $(call define-vendor-lib64,libSemDataProps,))
$(eval $(call define-vendor-lib64,libSemTelephonyProps,))
$(eval $(call define-vendor-lib64,libap2ap_calconversion,))
$(eval $(call define-vendor-lib64,libcodec2_sec_aacdec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_aacenc,))
$(eval $(call define-vendor-lib64,libcodec2_sec_amrnbdec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_amrwbdec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_flacdec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_imadec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_mp3dec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_mp4vdec,))
$(eval $(call define-vendor-lib64,libcodec2_sec_soft_common,))
$(eval $(call define-vendor-lib64,libcodec2_sec_vc1dec,))
$(eval $(call define-vendor-lib64,libcodec2_soft_ac4dec,))
$(eval $(call define-vendor-lib64,libcodec2_soft_eac3dec,))
$(eval $(call define-vendor-lib64,libdeccfg,))
$(eval $(call define-vendor-lib64,libdk_vnd_service_core,))
$(eval $(call define-vendor-lib64,libdlrmsc,))
$(eval $(call define-vendor-lib64,libdsms_vendor,))
$(eval $(call define-vendor-lib64,libdualcam_refocus_image,))
$(eval $(call define-vendor-lib64,libdualcam_refocus_video,))
$(eval $(call define-vendor-lib64,libengmode15,))
$(eval $(call define-vendor-lib64,libengmode2lite,))
$(eval $(call define-vendor-lib64,libengmode_client,))
$(eval $(call define-vendor-lib64,libengmode_server,))
$(eval $(call define-vendor-lib64,libengmode_tlc,))
$(eval $(call define-vendor-lib64,libexynoscamera3,))
$(eval $(call define-vendor-lib64,libhigh_dynamic_range_bokeh,))
$(eval $(call define-vendor-lib64,libhyper,))
$(eval $(call define-vendor-lib64,libhypervintf,))
$(eval $(call define-vendor-lib64,libremosaiclib,))
$(eval $(call define-vendor-lib64,libril_sem,))
$(eval $(call define-vendor-lib64,libsec-ril,))
$(eval $(call define-vendor-lib64,libsensorlistener,))
$(eval $(call define-vendor-lib64,libskeymint10device,))
$(eval $(call define-vendor-lib64,libskeymint_cli,))
$(eval $(call define-vendor-lib64,libsnap_compute,))
$(eval $(call define-vendor-lib64,libsnap_compute_wrapper,))
$(eval $(call define-vendor-lib64,libsnap_vndk,))
$(eval $(call define-vendor-lib64,libsnaplite_native,))
$(eval $(call define-vendor-lib64,libsnaplite_wrapper,))
$(eval $(call define-vendor-lib64,libsomxcmn,))
$(eval $(call define-vendor-lib64,libstork_shared,))
$(eval $(call define-vendor-lib64,libtlc_comm_iccc,))
$(eval $(call define-vendor-lib64,libtlc_direct_comm_iccc,))
$(eval $(call define-vendor-lib64,libtvm_runtime,))
$(eval $(call define-vendor-lib64,libtvm_wrapper,))
$(eval $(call define-vendor-lib64,libuniapi,))
$(eval $(call define-vendor-lib64,libvkmanager_vendor,))
$(eval $(call define-vendor-lib64,libvkservice,))
$(eval $(call define-vendor-lib64,nfc_nci.st21nfc.st,))
$(eval $(call define-vendor-lib64,service-listener-ext-aidl-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.frameworks.security.dsms-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.biometrics.fingerprint@3.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.bluetooth@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.camera.device@5.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.camera.device@5.0-impl,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.camera.provider@4.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.camera.provider@4.0-legacy,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.gnss@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.gnss@2.1,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.health-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.hyper-V2-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.keymint-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.light-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.miscpower@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.nfc_aidl-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.radio.bridge@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.radio.bridge@2.1,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.radio.channel@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.drk-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.engmode@1.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.fkeymaster-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.hdcp.wifidisplay-V2-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.vaultkeeper@2.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.security.widevine.keyprov-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.snap-V2-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.sysinput-V2-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.thermal-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.thermal@1.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.tlc.iccc@1.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.tlc.iccc@1.0-impl,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.tlc.kg@1.0,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.tlc.kg@1.1,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.vibrator-V5-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.wifi-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.wifi.nan-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.wifi.supplicant-V1-ndk,))
$(eval $(call define-vendor-lib64,vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0,))

# vendor/lib64/hw/ — 3 libs
$(eval $(call define-vendor-lib64,android.hardware.gnss@2.1-impl-samsung,hw))
$(eval $(call define-vendor-lib64,camera.exynos850,hw))
$(eval $(call define-vendor-lib64,vendor.samsung.hardware.gnss@2.1-impl,hw))

# ==========================================================
# SYSTEM PARTITION SHARED LIBRARIES
# ==========================================================

# system/lib + system/lib64 (MULTILIB BOTH)
define define-system-lib-both
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := both
  LOCAL_SRC_FILES_32        := proprietary/system/lib/$(1).so
  LOCAL_SRC_FILES_64        := proprietary/system/lib64/$(1).so
  include $$(BUILD_PREBUILT)
endef

$(eval $(call define-system-lib-both,libomafldrm))
$(eval $(call define-system-lib-both,vendor.samsung.frameworks.security.ucm.crypto@1.0))

# system/lib only (32-bit)
define define-system-lib32
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := 32
  LOCAL_SRC_FILES_32        := proprietary/system/lib/$(1).so
  include $$(BUILD_PREBUILT)
endef

$(eval $(call define-system-lib32,libhdcp2))
$(eval $(call define-system-lib32,libhdcp_client_aidl))
$(eval $(call define-system-lib32,libstagefright_hdcp))
$(eval $(call define-system-lib32,libstagefright_httplive_sec))
$(eval $(call define-system-lib32,vendor.samsung.hardware.security.hdcp.wifidisplay-V2-ndk))

# system/lib64 only (64-bit)
define define-system-lib64
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := SHARED_LIBRARIES
  LOCAL_MODULE_SUFFIX       := .so
  LOCAL_MODULE_TAGS         := optional
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := 64
  LOCAL_SRC_FILES_64        := proprietary/system/lib64/$(1).so
  include $$(BUILD_PREBUILT)
endef

$(eval $(call define-system-lib64,libcharon))
$(eval $(call define-system-lib64,libstrongswan))
$(eval $(call define-system-lib64,libucsengine.system))

# ==========================================================
# VENDOR EXECUTABLES (vendor/bin and vendor/bin/hw)
# ==========================================================

define define-vendor-bin
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := EXECUTABLES
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := first
  LOCAL_SRC_FILES           := proprietary/vendor/bin/$(1)
  include $$(BUILD_PREBUILT)
endef

define define-vendor-bin-hw
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := EXECUTABLES
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MODULE_RELATIVE_PATH := hw
  LOCAL_MULTILIB            := first
  LOCAL_SRC_FILES           := proprietary/vendor/bin/hw/$(1)
  include $$(BUILD_PREBUILT)
endef

# vendor/bin — 18 executables
$(eval $(call define-vendor-bin,argosd))
$(eval $(call define-vendor-bin,cass))
$(eval $(call define-vendor-bin,emservice))
$(eval $(call define-vendor-bin,fsdbg_vendor))
$(eval $(call define-vendor-bin,iod))
$(eval $(call define-vendor-bin,main_abox))
$(eval $(call define-vendor-bin,snap_utility_64))
$(eval $(call define-vendor-bin,tzdaemon))
$(eval $(call define-vendor-bin,tzts_daemon))
$(eval $(call define-vendor-bin,vaultkeeperd))
$(eval $(call define-vendor-bin,vendor.samsung.hardware.security.engmode@1.0-service))
$(eval $(call define-vendor-bin,vendor.samsung.hardware.security.fkeymaster-service))
$(eval $(call define-vendor-bin,vendor.samsung.hardware.security.hdcp.wifidisplay-service))
$(eval $(call define-vendor-bin,vendor.samsung.hardware.security.proca@2.0-service))
$(eval $(call define-vendor-bin,vendor.samsung.hardware.security.vaultkeeper@2.0-service))
$(eval $(call define-vendor-bin,wlbtd))
$(eval $(call define-vendor-bin,wvkprov))

# vendor/bin/hw — 30 executables
$(eval $(call define-vendor-bin-hw,android.hardware.drm@1.4-service.clearkey))
$(eval $(call define-vendor-bin-hw,android.hardware.drm@1.4-service.widevine))
$(eval $(call define-vendor-bin-hw,android.hardware.nfc-service-st))
$(eval $(call define-vendor-bin-hw,android.hardware.power.samsung-service))
$(eval $(call define-vendor-bin-hw,android.hardware.usb@1.3-service.coral))
$(eval $(call define-vendor-bin-hw,gpsd))
$(eval $(call define-vendor-bin-hw,macloader))
$(eval $(call define-vendor-bin-hw,mfgloader))
$(eval $(call define-vendor-bin-hw,samsung.hardware.media.c2@1.1-default-service))
$(eval $(call define-vendor-bin-hw,samsung.software.media.c2@1.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.biometrics.face-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.biometrics.fingerprint@3.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.camera.provider@4.0-service_64))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.gnss@2.1-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.health-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.hyper-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.light-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.miscpower@2.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.security.drk-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.security.drk@2.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.security.widevine.keyprov-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.snap-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.sysinput-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.thermal-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.tlc.iccc@1.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.tlc.kg@1.1-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.tlc.ucm@2.0-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.vibrator-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung.hardware.wifi-service))
$(eval $(call define-vendor-bin-hw,vendor.samsung_slsi.hardware.ExynosHWCServiceTW@1.0-service))

# ==========================================================
# VENDOR DATA FILES (non-ELF files found under vendor/bin)
# ==========================================================

define define-vendor-etc
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := ETC
  LOCAL_MODULE_TAGS         := optional
  LOCAL_PROPRIETARY_MODULE  := true
  LOCAL_MODULE_PATH         := $$(TARGET_OUT_VENDOR)/bin
  LOCAL_SRC_FILES           := proprietary/vendor/bin/$(2)
  include $$(BUILD_PREBUILT)
endef

$(eval $(call define-vendor-etc,add_tflite,add.tflite))
$(eval $(call define-vendor-etc,test_model_json,test_model.json))

# ==========================================================
# SYSTEM EXECUTABLES (system/bin)
# ==========================================================

define define-system-bin
  include $$(CLEAR_VARS)
  LOCAL_MODULE              := $(1)
  LOCAL_MODULE_CLASS        := EXECUTABLES
  LOCAL_MODULE_TAGS         := optional
  LOCAL_CHECK_ELF_FILES     := false
  LOCAL_MULTILIB            := first
  LOCAL_SRC_FILES           := proprietary/system/bin/$(1)
  include $$(BUILD_PREBUILT)
endef

$(eval $(call define-system-bin,charon_samsung))
